#
# configs
#

# quicker responsiveness
set -s escape-time 1

# start pane index on 1
set -g base-index 1
set -g pane-base-index 1

# show status bar on top
set-option -g status-position top

# renumber windows
set-option -g renumber-windows on

# enable mouse mode
set -g mouse on

# set color mode
set -g default-terminal "screen-256color"

#
# status bar
#

set -g status 'on'
set -g status-style 'fg=default,bg=default'
set -g status-left-style 'none'
set -g status-right-style 'none'
set -g status-justify 'centre'
set -g status-left-length '100'
set -g status-right-length '100'
set -g message-style 'fg=yellow,bg=default'
set -g message-command-style 'fg=yellow,bg=default'
set -g pane-border-style 'fg=brightblack'
set -g pane-active-border-style 'fg=green'
setw -g window-status-style 'fg=default,bg=default'
setw -g window-status-activity-style 'fg=yellow,bg=default'

# Left panel
set -g status-left '#[fg=green]「 #S 」'

# Window tab list
setw -g window-status-format '#[fg=cyan] #I #[fg=brightblack]⟫ #[fg=default]#W '
set -g window-status-separator '#[fg=brightblack]⁄'

# Window tab list active element
setw -g window-status-current-format '#[fg=green,bold] #I #[fg=brightblack,nobold]⟫ #[fg=green,bold]#W#[nobold] '

# Right panel
set -g status-right '#[fg=brightblack]  \
CPU: #[fg=green]#($HOME/dotfiles/tmux/display_cpu_usage.sh) #[fg=brightblack] | \
MEM: #[fg=green]#($HOME/dotfiles/tmux/display_mem_usage.sh)#[fg=brightblack]  | \
#[fg=green]%r  '

# window/session overview
setw -g mode-style 'reverse'

#
# binds
#
# window splitting
bind i split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# window and session overview
bind C-Space choose-session -s

# create new window in current session and ask for a name
bind-key c command-prompt -p "window name:" "new-window; rename-window '%%'"

# cretae new session and ask for a name
bind-key S command-prompt -p "session-name:" "new; rename-session '%%'"

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

#reload
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf has been sourced'

